
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/ariely122/.cache/JetBrains/RemoteDev/dist/7e91c9460ef4d_CLion-251.23774.202/bin/cmake/linux/x64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 5.15.167.4-microsoft-standard-WSL2 - x86_64
...
